// What Is The Move — mock Tampa dataset.
// All venues, places, and events below are MOCK / DEMO DATA for
// prototyping only. They do not represent real, currently scheduled
// events or confirmed venue/business information.

import type { Venue, PlaceItem, EventItem, Item } from "./types";

export const VENUES: Record<string, Venue> = {
  v_amphitheatre: { id: "v_amphitheatre", name: "MIDFLORIDA Credit Union Amphitheatre", neighborhood: "North Tampa", lat: 28.0075, lng: -82.3773 },
  v_sparkman: { id: "v_sparkman", name: "Sparkman Wharf", neighborhood: "Channelside", lat: 27.9421, lng: -82.4487 },
  v_berns: { id: "v_berns", name: "Bern's Steak House", neighborhood: "Hyde Park", lat: 27.9375, lng: -82.4823 },
  v_tropicana: { id: "v_tropicana", name: "Tropicana Field", neighborhood: "St. Petersburg", lat: 27.7683, lng: -82.6534 },
  v_armature: { id: "v_armature", name: "Armature Works", neighborhood: "Tampa Heights", lat: 27.9584, lng: -82.4595 },
  v_attic: { id: "v_attic", name: "The Attic Comedy Club", neighborhood: "Seminole Heights", lat: 28.0028, lng: -82.4574 },
  v_franklin: { id: "v_franklin", name: "Franklin Street", neighborhood: "Downtown Tampa", lat: 27.9506, lng: -82.4572 },
  v_bricks: { id: "v_bricks", name: "The Bricks", neighborhood: "Ybor City", lat: 27.9614, lng: -82.4392 },
  v_tma: { id: "v_tma", name: "Tampa Museum of Art", neighborhood: "Downtown Tampa", lat: 27.9481, lng: -82.4590 },
  v_blakes: { id: "v_blakes", name: "Blake's Uptown", neighborhood: "Hyde Park", lat: 27.9370, lng: -82.4830 },
  v_ground: { id: "v_ground", name: "The Ground", neighborhood: "Wynwood, Miami", lat: 25.8010, lng: -80.1990 },
  v_mbstadium: { id: "v_mbstadium", name: "Mercedes-Benz Stadium", neighborhood: "Downtown Atlanta", lat: 33.7554, lng: -84.4008 },
  v_amalie: { id: "v_amalie", name: "Amalie Arena", neighborhood: "Channel District", lat: 27.9427, lng: -82.4518 },
  v_sapporo: { id: "v_sapporo", name: "Sapporo Rooftop", neighborhood: "Water Street", lat: 27.9429, lng: -82.4551 },
  v_hpv: { id: "v_hpv", name: "Hyde Park Village", neighborhood: "Hyde Park", lat: 27.9385, lng: -82.4825 },
  v_ulele: { id: "v_ulele", name: "Ulele", neighborhood: "Tampa Heights", lat: 27.9590, lng: -82.4600 },
  v_rooftop555: { id: "v_rooftop555", name: "Rooftop 555", neighborhood: "Water Street", lat: 27.9435, lng: -82.4545 },
  v_bunker: { id: "v_bunker", name: "The Bunker Sports Bar", neighborhood: "Channel District", lat: 27.9430, lng: -82.4500 },
  v_wsplaza: { id: "v_wsplaza", name: "Water Street Plaza", neighborhood: "Water Street", lat: 27.9420, lng: -82.4560 },
  v_straz: { id: "v_straz", name: "Straz Center for the Performing Arts", neighborhood: "Downtown Tampa", lat: 27.9469, lng: -82.4602 },
  v_ybor7th: { id: "v_ybor7th", name: "7th Avenue", neighborhood: "Ybor City", lat: 27.9610, lng: -82.4380 },
  v_southernroots: { id: "v_southernroots", name: "Southern Roots", neighborhood: "Seminole Heights", lat: 28.0030, lng: -82.4580 },
  v_hallfranklin: { id: "v_hallfranklin", name: "The Hall on Franklin", neighborhood: "Downtown Tampa", lat: 27.9500, lng: -82.4575 },
};

// ---------------------- PLACES (12) — no fixed start/end, have hours ----------------------
export const PLACES: PlaceItem[] = [
  {
    id: "p1", type: "place", title: "Bern's Steak House", city: "Tampa", category: "Restaurant", subcategory: "Restaurant",
    venueId: "v_berns", cuisine: "Steakhouse", atmosphere: ["Upscale", "Good for Dates", "Worth Splurging"],
    priceLevel: "$$$$", hours: { thu: [17, 23], fri: [17, 23], sat: [17, 23], sun: [17, 22] },
    reservationUrl: "https://example.com/demo-reservations/berns", officialUrl: null,
    image: "https://picsum.photos/seed/bernssteak/900/700",
    tags: ["Upscale", "Good for Dates", "Foodie", "Luxury", "Worth Splurging"],
    badges: ["Editor's Pick", "Date Night"],
    description: "Tampa's benchmark splurge dinner, wine cellar tour included.",
    bestBetComponents: { significance: 82, venueQuality: 92, demand: 78, socialBuzz: 70, uniqueness: 75, value: 55 },
  },
  {
    id: "p2", type: "place", title: "Sapporo Rooftop", city: "Tampa", category: "Restaurant", subcategory: "Restaurant",
    venueId: "v_sapporo", cuisine: "Japanese / Omakase", atmosphere: ["Upscale", "Good for Dates", "Luxury"],
    priceLevel: "$$$$", hours: { thu: [17, 24], fri: [17, 24], sat: [17, 24], sun: [17, 23] },
    reservationUrl: "https://example.com/demo-reservations/sapporo", officialUrl: null,
    image: "https://picsum.photos/seed/sapporoomakase/900/700",
    tags: ["Upscale", "Good for Dates", "Foodie", "Luxury", "Worth Splurging"],
    badges: ["Worth the Trip", "Date Night"],
    description: "A 10-course omakase with skyline views a short walk from Water Street.",
    bestBetComponents: { significance: 80, venueQuality: 88, demand: 82, socialBuzz: 75, uniqueness: 80, value: 50 },
  },
  {
    id: "p3", type: "place", title: "Ulele", city: "Tampa", category: "Restaurant", subcategory: "Restaurant",
    venueId: "v_ulele", cuisine: "New American", atmosphere: ["Foodie", "Good for Groups", "Upscale"],
    priceLevel: "$$$", hours: { thu: [11, 22], fri: [11, 22], sat: [11, 22], sun: [11, 21] },
    reservationUrl: "https://example.com/demo-reservations/ulele", officialUrl: null,
    image: "https://picsum.photos/seed/ulelebrunch/900/700",
    tags: ["Foodie", "Good for Groups", "Daytime", "Upscale"],
    badges: ["Editor's Pick"],
    description: "Riverfront patio and house-brewed beer, best at brunch or golden hour.",
    bestBetComponents: { significance: 70, venueQuality: 78, demand: 74, socialBuzz: 65, uniqueness: 60, value: 68 },
  },
  {
    id: "p4", type: "place", title: "Sparkman Wharf Rooftop Bar", city: "Tampa", category: "Nightlife", subcategory: "Rooftop Bar",
    venueId: "v_sparkman", cuisine: null, atmosphere: ["Daytime", "High Energy", "Good for Groups", "Upscale"],
    priceLevel: "$$", hours: { thu: [12, 24], fri: [12, 26], sat: [12, 26], sun: [12, 23] },
    reservationUrl: null, officialUrl: "https://example.com/demo/sparkman-wharf",
    image: "https://picsum.photos/seed/rooftopsunset/900/700",
    tags: ["Daytime", "Good for Groups", "House", "Upscale", "Nightlife"],
    badges: ["Trending"],
    description: "Waterfront rooftop with a house-leaning DJ rotation most weekends.",
    bestBetComponents: { significance: 65, venueQuality: 72, demand: 74, socialBuzz: 68, uniqueness: 55, value: 72 },
  },
  {
    id: "p5", type: "place", title: "Armature Works Food Hall", city: "Tampa", category: "Restaurant", subcategory: "Restaurant",
    venueId: "v_armature", cuisine: "Food Hall", atmosphere: ["Foodie", "Culture", "Good for Dates"],
    priceLevel: "$$", hours: { thu: [11, 23], fri: [11, 24], sat: [11, 24], sun: [11, 22] },
    reservationUrl: null, officialUrl: "https://example.com/demo/armature-works",
    image: "https://picsum.photos/seed/armatureworks/900/700",
    tags: ["Foodie", "Culture", "Good for Dates", "Good for Groups"],
    badges: [],
    description: "A dozen stalls under one roof on the riverwalk — easy for mixed tastes.",
    bestBetComponents: { significance: 60, venueQuality: 70, demand: 65, socialBuzz: 60, uniqueness: 55, value: 78 },
  },
  {
    id: "p6", type: "place", title: "The Bricks Basement Lounge", city: "Tampa", category: "Nightlife", subcategory: "Lounge",
    venueId: "v_bricks", cuisine: null, atmosphere: ["Nightlife", "High Energy", "Singles"],
    priceLevel: "$$", hours: { thu: [21, 27], fri: [21, 28], sat: [21, 28], sun: [21, 26] },
    reservationUrl: null, officialUrl: "https://example.com/demo/the-bricks",
    image: "https://picsum.photos/seed/basementhouse/900/700",
    tags: ["Nightlife", "House", "High Energy", "Singles"],
    badges: ["Selling Fast"],
    description: "Underground house sets that run until 4am most weekends.",
    bestBetComponents: { significance: 62, venueQuality: 58, demand: 68, socialBuzz: 60, uniqueness: 55, value: 80 },
  },
  {
    id: "p7", type: "place", title: "Blake's Uptown", city: "Tampa", category: "Nightlife", subcategory: "Lounge",
    venueId: "v_blakes", cuisine: null, atmosphere: ["Live Music", "Chill", "Good for Dates", "Good for Groups"],
    priceLevel: "$", hours: { thu: [18, 25], fri: [18, 25], sat: [18, 25], sun: [18, 24] },
    reservationUrl: null, officialUrl: "https://example.com/demo/blakes-uptown",
    image: "https://picsum.photos/seed/salsanightblakes/900/700",
    tags: ["Live Music", "Good for Dates", "Chill", "Good for Groups"],
    badges: [],
    description: "Low-pressure live-music lounge, easy for a mixed group.",
    bestBetComponents: { significance: 48, venueQuality: 55, demand: 50, socialBuzz: 42, uniqueness: 60, value: 88 },
  },
  {
    id: "p8", type: "place", title: "Hyde Park Village Cafe & Bar", city: "Tampa", category: "Culture", subcategory: "Bar",
    venueId: "v_hpv", cuisine: "Cafe", atmosphere: ["Chill", "Outdoors", "Good for Dates"],
    priceLevel: "$", hours: { thu: [16, 22], fri: [16, 23], sat: [10, 23], sun: [10, 21] },
    reservationUrl: null, officialUrl: null,
    image: "https://picsum.photos/seed/hpvnightmarket/900/700",
    tags: ["Outdoors", "Good for Dates", "Chill", "Daytime"],
    badges: [],
    description: "String lights and an easy patio — good for a pre-dinner drink.",
    bestBetComponents: { significance: 40, venueQuality: 55, demand: 42, socialBuzz: 38, uniqueness: 45, value: 85 },
  },
  {
    id: "p9", type: "place", title: "Southern Roots Brunch House", city: "Tampa", category: "Restaurant", subcategory: "Restaurant",
    venueId: "v_southernroots", cuisine: "Southern / Brunch", atmosphere: ["Foodie", "Daytime", "Good for Groups"],
    priceLevel: "$$", hours: { sat: [9, 15], sun: [9, 15] },
    reservationUrl: "https://example.com/demo-reservations/southern-roots", officialUrl: null,
    image: "https://picsum.photos/seed/southernroots/900/700",
    tags: ["Foodie", "Daytime", "Good for Groups"],
    badges: ["Hidden Gem"],
    description: "Weekend-only brunch spot with a wait worth having.",
    bestBetComponents: { significance: 55, venueQuality: 62, demand: 60, socialBuzz: 55, uniqueness: 65, value: 75 },
  },
  {
    id: "p10", type: "place", title: "The Bunker Sports Bar", city: "Tampa", category: "Sports", subcategory: "Bar",
    venueId: "v_bunker", cuisine: "American / Bar Food", atmosphere: ["Sports", "Good for Groups"],
    priceLevel: "$", hours: { thu: [11, 26], fri: [11, 26], sat: [11, 26], sun: [11, 25] },
    reservationUrl: null, officialUrl: null,
    image: "https://picsum.photos/seed/bunkersportsbar/900/700",
    tags: ["Sports", "Good for Groups"],
    badges: [],
    description: "Every game on, every screen — the easy default for watch parties.",
    bestBetComponents: { significance: 42, venueQuality: 50, demand: 45, socialBuzz: 38, uniqueness: 35, value: 90 },
  },
  {
    id: "p11", type: "place", title: "Rooftop 555", city: "Tampa", category: "Nightlife", subcategory: "Rooftop Bar",
    venueId: "v_rooftop555", cuisine: null, atmosphere: ["Upscale", "Good for Dates", "Nightlife", "High Energy"],
    priceLevel: "$$$", hours: { thu: [17, 25], fri: [17, 26], sat: [17, 26], sun: [17, 24] },
    reservationUrl: null, officialUrl: "https://example.com/demo/rooftop-555",
    image: "https://picsum.photos/seed/rooftop555/900/700",
    tags: ["Upscale", "Good for Dates", "Nightlife", "High Energy", "Good for Groups"],
    badges: ["Trending"],
    description: "Skyline views two blocks from Water Street — dressy but not stuffy.",
    bestBetComponents: { significance: 68, venueQuality: 80, demand: 76, socialBuzz: 70, uniqueness: 58, value: 65 },
  },
  {
    id: "p12", type: "place", title: "The Hall on Franklin", city: "Tampa", category: "Restaurant", subcategory: "Restaurant",
    venueId: "v_hallfranklin", cuisine: "Food Hall / Bar", atmosphere: ["Good for Groups", "Casual"],
    priceLevel: "$$", hours: { thu: [11, 24], fri: [11, 25], sat: [11, 25], sun: [11, 23] },
    reservationUrl: null, officialUrl: "https://example.com/demo/hall-on-franklin",
    image: "https://picsum.photos/seed/hallfranklin/900/700",
    tags: ["Good for Groups", "Foodie"],
    badges: [],
    description: "Downtown food hall with a full bar — flexible for a mixed group.",
    bestBetComponents: { significance: 45, venueQuality: 58, demand: 50, socialBuzz: 42, uniqueness: 40, value: 82 },
  },
];

// ---------------------- EVENTS (20) — ISO start/end, ticketed or scheduled ----------------------
export const EVENTS: EventItem[] = [
  {
    id: "e1", type: "event", title: "KAYTRANADA", city: "Tampa", category: "Nightlife", subcategory: "DJ Set",
    venueId: "v_amphitheatre", performer: "KAYTRANADA",
    startTime: "2026-09-18T21:00:00", endTime: "2026-09-18T23:30:00",
    priceMin: 65, priceMax: 140, ticketUrl: "https://example.com/demo-tickets/kaytranada", officialUrl: null,
    image: "https://picsum.photos/seed/kaytranada/900/700",
    tags: ["Nightlife", "Hip Hop", "R&B", "House", "High Energy"], badges: ["🔥 Hot", "Selling Fast"],
    description: "One of the strongest music bookings in Tampa this month.",
    bestBetComponents: { significance: 95, venueQuality: 80, demand: 94, socialBuzz: 90, uniqueness: 70, value: 60 },
  },
  {
    id: "e2", type: "event", title: "Rooftop Sunset Sessions", city: "Tampa", category: "Nightlife", subcategory: "Day Party",
    venueId: "v_sparkman", performer: null,
    startTime: "2026-09-12T16:00:00", endTime: "2026-09-12T20:00:00",
    priceMin: 20, priceMax: 40, ticketUrl: null, officialUrl: "https://example.com/demo/rooftop-sunset-sessions",
    image: "https://picsum.photos/seed/rooftopsunsetevent/900/700",
    tags: ["Daytime", "Good for Groups", "House", "Upscale"], badges: ["Group Move"],
    description: "House-music day party with water views, starting right now.",
    bestBetComponents: { significance: 70, venueQuality: 75, demand: 72, socialBuzz: 68, uniqueness: 55, value: 75 },
  },
  {
    id: "e4", type: "event", title: "Rays vs. Orioles", city: "Tampa", category: "Sports", subcategory: "MLB",
    venueId: "v_tropicana", performer: null,
    startTime: "2026-09-12T18:10:00", endTime: "2026-09-12T21:00:00",
    priceMin: 25, priceMax: 95, ticketUrl: "https://example.com/demo-tickets/rays-orioles", officialUrl: null,
    image: "https://picsum.photos/seed/raysgame/900/700",
    tags: ["Sports", "Good for Groups", "Daytime"], badges: ["Group Move"],
    description: "Late-season divisional game with fireworks after.",
    bestBetComponents: { significance: 60, venueQuality: 65, demand: 68, socialBuzz: 50, uniqueness: 40, value: 70 },
  },
  {
    id: "e5", type: "event", title: "Uncorked: Natural Wine Pop-Up", city: "Tampa", category: "Culture", subcategory: "Pop Up",
    venueId: "v_armature", performer: null,
    startTime: "2026-09-12T18:00:00", endTime: "2026-09-12T21:00:00",
    priceMin: 35, priceMax: 60, ticketUrl: null, officialUrl: "https://example.com/demo/uncorked-popup",
    image: "https://picsum.photos/seed/unwinepopup/900/700",
    tags: ["Foodie", "Culture", "Good for Dates", "Upscale"], badges: ["Hidden Gem", "Worth the Trip"],
    description: "A one-night natural wine pop-up from a Miami collective.",
    bestBetComponents: { significance: 75, venueQuality: 78, demand: 80, socialBuzz: 85, uniqueness: 88, value: 65 },
  },
  {
    id: "e6", type: "event", title: "Tampa Comedy Underground", city: "Tampa", category: "Comedy", subcategory: "Stand-Up",
    venueId: "v_attic", performer: null,
    startTime: "2026-09-18T20:30:00", endTime: "2026-09-18T22:30:00",
    priceMin: 20, priceMax: 35, ticketUrl: "https://example.com/demo-tickets/comedy-underground", officialUrl: null,
    image: "https://picsum.photos/seed/attic-comedy/900/700",
    tags: ["Good for Groups", "Good for Dates", "Chill"], badges: [],
    description: "Rotating lineup of touring comics in a 90-seat room.",
    bestBetComponents: { significance: 55, venueQuality: 60, demand: 58, socialBuzz: 45, uniqueness: 50, value: 80 },
  },
  {
    id: "e7", type: "event", title: "Gasparilla Music & Arts Block Party", city: "Tampa", category: "Festival", subcategory: "Street Festival",
    venueId: "v_franklin", performer: null,
    startTime: "2026-09-12T14:00:00", endTime: "2026-09-12T20:00:00",
    priceMin: 0, priceMax: 25, ticketUrl: null, officialUrl: "https://example.com/demo/gasparilla-block-party",
    image: "https://picsum.photos/seed/gasparillablock/900/700",
    tags: ["Outdoors", "Culture", "Good for Groups", "Daytime"], badges: ["Free", "Trending"],
    description: "Local bands, food trucks, and makers downtown all afternoon.",
    bestBetComponents: { significance: 72, venueQuality: 60, demand: 75, socialBuzz: 70, uniqueness: 60, value: 95 },
  },
  {
    id: "e8", type: "event", title: "Late Night House — Basement Set", city: "Tampa", category: "Nightlife", subcategory: "DJ Set",
    venueId: "v_bricks", performer: null,
    startTime: "2026-09-12T23:00:00", endTime: "2026-09-13T03:00:00",
    priceMin: 15, priceMax: 30, ticketUrl: "https://example.com/demo-tickets/basement-house", officialUrl: null,
    image: "https://picsum.photos/seed/basementhouseevent/900/700",
    tags: ["Nightlife", "House", "High Energy", "Singles"], badges: ["Selling Fast"],
    description: "Underground house set running until 3am.",
    bestBetComponents: { significance: 65, venueQuality: 58, demand: 70, socialBuzz: 62, uniqueness: 55, value: 85 },
  },
  {
    id: "e10", type: "event", title: "Tampa Museum of Art — After Hours", city: "Tampa", category: "Culture", subcategory: "Exhibition",
    venueId: "v_tma", performer: null,
    startTime: "2026-09-18T18:00:00", endTime: "2026-09-18T21:00:00",
    priceMin: 15, priceMax: 25, ticketUrl: "https://example.com/demo-tickets/tma-after-hours", officialUrl: null,
    image: "https://picsum.photos/seed/tmaafterhours/900/700",
    tags: ["Culture", "Good for Dates", "Chill"], badges: [],
    description: "Late-opening night with a DJ in the courtyard.",
    bestBetComponents: { significance: 58, venueQuality: 70, demand: 50, socialBuzz: 45, uniqueness: 60, value: 80 },
  },
  {
    id: "e11", type: "event", title: "Salsa Night at Blake's", city: "Tampa", category: "Nightlife", subcategory: "Live Music",
    venueId: "v_blakes", performer: null,
    startTime: "2026-09-17T21:00:00", endTime: "2026-09-17T23:00:00",
    priceMin: 10, priceMax: 20, ticketUrl: null, officialUrl: "https://example.com/demo/salsa-night-blakes",
    image: "https://picsum.photos/seed/salsanightblakesevent/900/700",
    tags: ["Live Music", "Good for Dates", "Chill", "Good for Groups"], badges: [],
    description: "Free lessons at 9, live band after.",
    bestBetComponents: { significance: 45, venueQuality: 55, demand: 48, socialBuzz: 40, uniqueness: 65, value: 90 },
  },
  {
    id: "e13", type: "event", title: "Miami Music Week Preview Warehouse Set", city: "Miami", category: "Nightlife", subcategory: "DJ Set",
    venueId: "v_ground", performer: null,
    startTime: "2026-09-19T22:00:00", endTime: "2026-09-20T03:00:00",
    priceMin: 55, priceMax: 120, ticketUrl: "https://example.com/demo-tickets/miami-warehouse", officialUrl: null,
    image: "https://picsum.photos/seed/miamiwarehouse/900/700",
    tags: ["Nightlife", "House", "EDM", "High Energy"], badges: ["Worth the Trip", "🔥 Hot"],
    description: "A genuinely significant lineup ahead of Miami Music Week.",
    bestBetComponents: { significance: 92, venueQuality: 75, demand: 90, socialBuzz: 88, uniqueness: 80, value: 55 },
  },
  {
    id: "e14", type: "event", title: "Falcons Home Opener", city: "Atlanta", category: "Sports", subcategory: "NFL",
    venueId: "v_mbstadium", performer: null,
    startTime: "2026-09-13T13:00:00", endTime: "2026-09-13T16:00:00",
    priceMin: 80, priceMax: 250, ticketUrl: "https://example.com/demo-tickets/falcons-opener", officialUrl: null,
    image: "https://picsum.photos/seed/atlfalcons/900/700",
    tags: ["Sports", "Good for Groups", "High Energy"], badges: ["Worth the Trip"],
    description: "Home opener with real stakes and a strong tailgate scene.",
    bestBetComponents: { significance: 88, venueQuality: 85, demand: 90, socialBuzz: 75, uniqueness: 70, value: 45 },
  },
  {
    id: "e15", type: "event", title: "Amalie Arena — Comedy Headliner", city: "Tampa", category: "Comedy", subcategory: "Arena Show",
    venueId: "v_amalie", performer: null,
    startTime: "2026-09-12T20:00:00", endTime: "2026-09-12T22:00:00",
    priceMin: 60, priceMax: 150, ticketUrl: "https://example.com/demo-tickets/amalie-comedy", officialUrl: null,
    image: "https://picsum.photos/seed/amaliecomedy/900/700",
    tags: ["Good for Dates", "Good for Groups", "Upscale"], badges: ["Selling Fast", "Editor's Pick"],
    description: "A major touring headliner making a rare Tampa stop.",
    bestBetComponents: { significance: 85, venueQuality: 82, demand: 88, socialBuzz: 78, uniqueness: 65, value: 55 },
  },
  {
    id: "e16", type: "event", title: "Hyde Park Village Night Market", city: "Tampa", category: "Culture", subcategory: "Pop Up",
    venueId: "v_hpv", performer: null,
    startTime: "2026-09-17T18:00:00", endTime: "2026-09-17T21:00:00",
    priceMin: 0, priceMax: 20, ticketUrl: null, officialUrl: "https://example.com/demo/hpv-night-market",
    image: "https://picsum.photos/seed/hpvnightmarketevent/900/700",
    tags: ["Outdoors", "Good for Dates", "Chill", "Daytime"], badges: ["Free"],
    description: "Local vendors and live acoustic music before dinner.",
    bestBetComponents: { significance: 40, venueQuality: 50, demand: 42, socialBuzz: 38, uniqueness: 55, value: 95 },
  },
  {
    id: "e17", type: "event", title: "The Groove Collective — Live R&B Band", city: "Tampa", category: "Nightlife", subcategory: "Live Music",
    venueId: "v_rooftop555", performer: "The Groove Collective",
    startTime: "2026-09-12T21:00:00", endTime: "2026-09-13T01:00:00",
    priceMin: 0, priceMax: 25, ticketUrl: null, officialUrl: "https://example.com/demo/groove-collective",
    image: "https://picsum.photos/seed/groovecollective/900/700",
    tags: ["Live Music", "R&B", "Upscale", "High Energy", "Good for Groups"], badges: ["Trending"],
    description: "A live R&B band at an upscale rooftop — lively without being a club.",
    bestBetComponents: { significance: 68, venueQuality: 80, demand: 75, socialBuzz: 72, uniqueness: 60, value: 85 },
  },
  {
    id: "e18", type: "event", title: "Sports Bar Watch Party", city: "Tampa", category: "Sports", subcategory: "Watch Party",
    venueId: "v_bunker", performer: null,
    startTime: "2026-09-13T15:00:00", endTime: "2026-09-13T20:00:00",
    priceMin: 0, priceMax: 15, ticketUrl: null, officialUrl: null,
    image: "https://picsum.photos/seed/sportsbarwatch/900/700",
    tags: ["Sports", "Good for Groups", "Chill"], badges: [],
    description: "Every game on, every screen, casual and free to walk in.",
    bestBetComponents: { significance: 38, venueQuality: 50, demand: 40, socialBuzz: 35, uniqueness: 45, value: 95 },
  },
  {
    id: "e19", type: "event", title: "Water Street Jazz & Whiskey Night", city: "Tampa", category: "Nightlife", subcategory: "Live Music",
    venueId: "v_wsplaza", performer: null,
    startTime: "2026-09-12T20:00:00", endTime: "2026-09-12T23:00:00",
    priceMin: 20, priceMax: 45, ticketUrl: "https://example.com/demo-tickets/jazz-whiskey", officialUrl: null,
    image: "https://picsum.photos/seed/jazzwhiskey/900/700",
    tags: ["Live Music", "Jazz", "Upscale", "Good for Dates"], badges: [],
    description: "Jazz trio and a whiskey list, two minutes from Water Street.",
    bestBetComponents: { significance: 62, venueQuality: 78, demand: 65, socialBuzz: 58, uniqueness: 70, value: 75 },
  },
  {
    id: "e20", type: "event", title: "Straz Center — Broadway Touring Show", city: "Tampa", category: "Culture", subcategory: "Theater",
    venueId: "v_straz", performer: null,
    startTime: "2026-09-18T19:30:00", endTime: "2026-09-18T22:00:00",
    priceMin: 45, priceMax: 130, ticketUrl: "https://example.com/demo-tickets/straz-broadway", officialUrl: null,
    image: "https://picsum.photos/seed/strazbroadway/900/700",
    tags: ["Culture", "Upscale", "Good for Dates"], badges: [],
    description: "A touring Broadway production for one week only.",
    bestBetComponents: { significance: 80, venueQuality: 85, demand: 70, socialBuzz: 55, uniqueness: 65, value: 50 },
  },
  {
    id: "e21", type: "event", title: "Ybor Saturday Street Festival: Salsa & Sounds", city: "Tampa", category: "Festival", subcategory: "Street Festival",
    venueId: "v_ybor7th", performer: null,
    startTime: "2026-09-12T17:00:00", endTime: "2026-09-12T23:00:00",
    priceMin: 0, priceMax: 20, ticketUrl: null, officialUrl: "https://example.com/demo/ybor-street-festival",
    image: "https://picsum.photos/seed/yborfestival/900/700",
    tags: ["Outdoors", "Culture", "Good for Groups", "High Energy"], badges: ["Free"],
    description: "7th Avenue closes for salsa lessons, live sets, and food vendors.",
    bestBetComponents: { significance: 58, venueQuality: 55, demand: 60, socialBuzz: 62, uniqueness: 50, value: 95 },
  },
  {
    id: "e22", type: "event", title: "Lightning Preseason Watch Party", city: "Tampa", category: "Sports", subcategory: "Watch Party",
    venueId: "v_amalie", performer: null,
    startTime: "2026-09-13T18:00:00", endTime: "2026-09-13T21:00:00",
    priceMin: 0, priceMax: 20, ticketUrl: null, officialUrl: null,
    image: "https://picsum.photos/seed/lightningwatch/900/700",
    tags: ["Sports", "Good for Groups"], badges: [],
    description: "Free plaza watch party outside Amalie Arena.",
    bestBetComponents: { significance: 45, venueQuality: 60, demand: 48, socialBuzz: 42, uniqueness: 40, value: 95 },
  },
  {
    id: "e23", type: "event", title: "Encore: Rooftop Day-to-Night House Session", city: "Tampa", category: "Nightlife", subcategory: "DJ Set",
    venueId: "v_sparkman", performer: null,
    startTime: "2026-09-12T19:00:00", endTime: "2026-09-13T00:00:00",
    priceMin: 25, priceMax: 55, ticketUrl: "https://example.com/demo-tickets/encore-rooftop", officialUrl: null,
    image: "https://picsum.photos/seed/encorerooftop/900/700",
    tags: ["Nightlife", "House", "High Energy", "Upscale", "Good for Groups"], badges: ["Trending"],
    description: "The rooftop's day party rolls into a full DJ set after dark.",
    bestBetComponents: { significance: 70, venueQuality: 75, demand: 78, socialBuzz: 74, uniqueness: 58, value: 70 },
  },
];

export const ALL_ITEMS: Item[] = [...PLACES, ...EVENTS];
